### ISSUE TITLE
IT LACKS KANGING

### ISSUE THREAD

**Issue by ghost** [ping2109/Neva-Kernel-v2#1]
SAR KANG WEN

**Comment by ping2109** [comment]
SOON SAR 
WILL KANG INSTANTLY WHEN I GET FLAMEKERNEL SOURCE 🥰🥰😍😍😍😍😍😍😍😘😘😘😘😘😘

**Comment by ghost** [comment]
MAKE IT HAPPEN, 3000000000 FPS ON PUBG KARNAL NAIS
